language: scala

jdk: oraclejdk8

scala:
- 2.12.6

sudo: false

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete